import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

class PdfService {
  Future<File> generateReport({
    required String title,
    required String dateLabel,
    required Map<int, Map<String, double>> dailyLogs,
    required int cycleLength,
  }) async {
    final sortedDays = dailyLogs.keys.toList()..sort();
    final doc = pw.Document();

    double avg(String key) {
      if (sortedDays.isEmpty) return 0;
      final values = sortedDays.map((d) => dailyLogs[d]![key] ?? 0).toList();
      return values.reduce((a, b) => a + b) / values.length;
    }

    final avgPain = avg('pain');
    final avgFatigue = avg('fatigue');
    final avgMood = avg('mood');
    final avgBloating = avg('bloating');

    String topSymptomNote = 'Not enough data logged yet to identify a leading symptom.';
    if (sortedDays.isNotEmpty) {
      final ranked = [
        MapEntry('pain', avgPain),
        MapEntry('fatigue', avgFatigue),
        MapEntry('bloating', avgBloating),
      ]..sort((a, b) => b.value.compareTo(a.value));
      topSymptomNote = 'Highest average symptom: ${ranked.first.key} at ${ranked.first.value.toStringAsFixed(1)}/10.';
    }

    doc.addPage(
      pw.Page(
        build: (context) => pw.Padding(
          padding: const pw.EdgeInsets.all(32),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('Cadence', style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 4),
              pw.Text('PCOS Care Companion', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
              pw.SizedBox(height: 24),
              pw.Text(title, style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.Text(dateLabel, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
              pw.SizedBox(height: 20),
              pw.Text('Summary', style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 6),
              pw.Text(
                sortedDays.isEmpty
                    ? 'No symptoms have been logged yet for this cycle. Once entries are logged from the Today tab, this report will summarize them here.'
                    : '${sortedDays.length} of $cycleLength cycle days have been logged. The figures below are self-reported averages from those entries, not a clinical assessment.',
                style: const pw.TextStyle(fontSize: 11),
              ),
              pw.SizedBox(height: 20),
              if (sortedDays.isNotEmpty) ...[
                pw.Text('Average symptom levels (0–10)', style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 8),
                pw.Table(
                  columnWidths: const {0: pw.FlexColumnWidth(2), 1: pw.FlexColumnWidth(1)},
                  children: [
                    _row('Pain', avgPain),
                    _row('Fatigue', avgFatigue),
                    _row('Mood', avgMood),
                    _row('Bloating', avgBloating),
                  ],
                ),
                pw.SizedBox(height: 20),
                pw.Text('Notes for your doctor', style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 6),
                pw.Bullet(text: topSymptomNote),
                pw.Bullet(text: 'Logged days: ${sortedDays.map((d) => 'Day $d').join(', ')}'),
              ],
              pw.Spacer(),
              pw.Divider(),
              pw.Text(
                'Generated by Cadence. Patterns shown are based on self-reported logs and are not a medical diagnosis.',
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
              ),
            ],
          ),
        ),
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final safeName = title.replaceAll(RegExp(r'[^\w\s-]'), '').replaceAll(' ', '_');
    final file = File('${dir.path}/$safeName.pdf');
    await file.writeAsBytes(await doc.save());
    return file;
  }

  pw.TableRow _row(String label, double value) {
    return pw.TableRow(
      children: [
        pw.Padding(
          padding: const pw.EdgeInsets.symmetric(vertical: 4),
          child: pw.Text(label, style: const pw.TextStyle(fontSize: 11)),
        ),
        pw.Padding(
          padding: const pw.EdgeInsets.symmetric(vertical: 4),
          child: pw.Text(value.toStringAsFixed(1), style: const pw.TextStyle(fontSize: 11)),
        ),
      ],
    );
  }

  Future<void> shareReport(File file) async {
    await Share.shareXFiles([XFile(file.path)], text: 'Cadence cycle report');
  }
}