// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC17XVV7csvT8JJfHMpp_-B0f3uryY1YpM',
    appId: '1:492077834729:web:62f182aaf61516061b2b78',
    messagingSenderId: '492077834729',
    projectId: 'cadence-91b81',
    authDomain: 'cadence-91b81.firebaseapp.com',
    storageBucket: 'cadence-91b81.firebasestorage.app',
    measurementId: 'G-JXYF54XDBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARciQ_67eEgNIxevTScTl-GnT_Oh6AZ5E',
    appId: '1:492077834729:android:bdec7eb5d90308b81b2b78',
    messagingSenderId: '492077834729',
    projectId: 'cadence-91b81',
    storageBucket: 'cadence-91b81.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2SS239f0SmMvFGU3K3xFBCwQxMEoDxmU',
    appId: '1:492077834729:ios:9bd55f6de71e98f51b2b78',
    messagingSenderId: '492077834729',
    projectId: 'cadence-91b81',
    storageBucket: 'cadence-91b81.firebasestorage.app',
    iosClientId: '492077834729-hkh27egm7qdnh261774mltc9ask8rba4.apps.googleusercontent.com',
    iosBundleId: 'com.example.cadence',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2SS239f0SmMvFGU3K3xFBCwQxMEoDxmU',
    appId: '1:492077834729:ios:9bd55f6de71e98f51b2b78',
    messagingSenderId: '492077834729',
    projectId: 'cadence-91b81',
    storageBucket: 'cadence-91b81.firebasestorage.app',
    iosClientId: '492077834729-hkh27egm7qdnh261774mltc9ask8rba4.apps.googleusercontent.com',
    iosBundleId: 'com.example.cadence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC17XVV7csvT8JJfHMpp_-B0f3uryY1YpM',
    appId: '1:492077834729:web:796c331e7a3d4acc1b2b78',
    messagingSenderId: '492077834729',
    projectId: 'cadence-91b81',
    authDomain: 'cadence-91b81.firebaseapp.com',
    storageBucket: 'cadence-91b81.firebasestorage.app',
    measurementId: 'G-HTJZL1Q4T1',
  );
}
